language: php

php:
  - 7.1
  - 7.2

sudo: required

dist: xenial

install:
  - travis_retry composer install --no-interaction --prefer-dist

script:
  - vendor/bin/php-cs-fixer fix --dry-run || travis_terminate 1
  - vendor/bin/phpstan analyse -l max --no-interaction --no-progress -- AbstractDatadogService.php || travis_terminate 1
  - vendor/bin/phpspec run
